### ISSUE TITLE
Incompatible mod set

### ISSUE THREAD

**Issue by EldraTheThird** [getchoo/threadtweak#6]
This mod is stated to support from 1.20 and higher, but when I install the mod with Fabric 1.20 an error occurs incompatibility with version 1.20. It's strange
![image](https://github.com/getchoo/threadtweak/assets/108326998/b820b7e7-b272-4417-80e7-94c4673da4dd)

![image](https://github.com/getchoo/threadtweak/assets/108326998/37e5f09b-a794-4b54-96c6-17a73c4bfac1)

**Comment by offbeat-stuff** [comment]
try 1.20.1

**Comment by EldraTheThird** [comment]
Yes, 1.20.1 it works fine. I hope the author will update for 1.20
